name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      gem_compare_version:
        description: 'Version of the gem-compare plugin'
        required: false
        type: string
      name:
        description: 'Name of gem to compare'
        required: false
        type: string
      from:
        description: 'From version'
        required: false
        type: string
      to:
        description: 'To version'
        required: false
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GEM_COMPARE_VERSION: ${{ inputs.gem_compare_version || '1.1.0' }}
      COMPARE_GEM: ${{ inputs.name || 'pg' }}
      COMPARE_FROM_VERSION: ${{ inputs.from || '1.4.0' }}
      COMPARE_TO_VERSION: ${{ inputs.to || '1.4.1' }}
    steps:
      - uses: ./
        with:
          gem_compare_version: $GEM_COMPARE_VERSION
          name: $COMPARE_GEM
          from: $COMPARE_FROM_VERSION
          to: $COMPARE_TO_VERSION
          github-token: ${{ secrets.GITHUB_TOKEN }}
