name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of gem to compare'
        required: false
        type: string
      from:
        description: 'From version'
        required: false
        type: string
      to:
        description: 'To version'
        required: false
        type: string
      pr:
        description: 'The number of the pull request to comment in'
        required: false
        type: number

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          pr_title: "Bump ${{ inputs.name || 'pg' }} from ${{ inputs.from || '1.4.0' }} to ${{ inputs.to || '1.4.1' }}"
          pr_number: ${{ inputs.pr || 1 }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
