name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      gem_compare_version:
        description: 'Version of the gem-compare plugin'
        required: false
        type: string
      name:
        description: 'Name of gem to compare'
        required: false
        type: string
      from:
        description: 'From version'
        required: false
        type: string
      to:
        description: 'To version'
        required: false
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
