name: CI
on:
  push:
  workflow_dispatch:
    inputs:
      gem_compare_version:
        description: 'Version of the gem-compare plugin'
        required: false
        type: string
      name:
        description: 'Name of gem to compare'
        required: false
        type: string
      from:
        description: 'From version'
        required: false
        type: string
      to:
        description: 'To version'
        required: false
        type: string

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GEM_COMPARE_VERSION: ${{ inputs.gem_compare_version || '1.1.0' }}
      COMPARE_GEM: ${{ inputs.name || 'pg' }}
      COMPARE_FROM_VERSION: ${{ inputs.from || '1.4.0' }}
      COMPARE_TO_VERSION: ${{ inputs.to || '1.4.1' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: "Run gem install gem-compare --version $GEM_COMPARE_VERSION"
        run: |
          gem install gem-compare --version $GEM_COMPARE_VERSION
      - name: "Run gem compare $COMPARE_GEM $COMPARE_FROM_VERSION $COMPARE_TO_VERSION"
        run: |
          echo 'COMPARE_OUTPUT<<EOF' >> $GITHUB_ENV
          gem compare $COMPARE_GEM $COMPARE_FROM_VERSION $COMPARE_TO_VERSION >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: "Run gem compare --diff $COMPARE_GEM $COMPARE_FROM_VERSION $COMPARE_TO_VERSION"
        run: |
          echo 'COMPARE_DIFF_OUTPUT<<EOF' >> $GITHUB_ENV
          gem compare --diff $COMPARE_GEM $COMPARE_FROM_VERSION $COMPARE_TO_VERSION >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Run gh pr comment
        run: |
          echo "## <code>gem compare $COMPARE_GEM $COMPARE_FROM_VERSION $COMPARE_TO_VERSION</code>" > comment.txt
          echo ''                        >> comment.txt
          echo '````ruby'                >> comment.txt
          echo "$COMPARE_OUTPUT"         >> comment.txt
          echo '````'                    >> comment.txt

          echo "## <code>gem compare --diff $COMPARE_GEM $COMPARE_FROM_VERSION $COMPARE_TO_VERSION</code>" >> comment.txt
          echo ''                        >> comment.txt
          echo '````bash'                >> comment.txt
          echo "$COMPARE_DIFF_OUTPUT"    >> comment.txt
          echo '````'                    >> comment.txt

          gh pr comment 1 --body-file comment.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
